### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'baidu-map'.

### ISSUE THREAD

**Issue by itshu** [leftstick/angular2-baidu-map#15]
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'baidu-map'.
1. If 'baidu-map' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'baidu-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        <h1>Test Baidu-Map<h1>
        <baidu-map ak="8f2MyxGBGMgB8NTcFkQ46RXbP5srlg9g" [ERROR ->][options]="opts" [offline]="offlineOpts" (onMapLoaded)="loadMap($event)" (onMarkerClicked)="clickMark"): MapPage@2:57
Can't bind to 'offline' since it isn't a known property of 'baidu-map'.
1. If 'baidu-map' is an Angular component and it has 'offline' input, then verify that it is part of this module.
2. If 'baidu-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("   <h1>Test Baidu-Map<h1>
        <baidu-map ak="8f2MyxGBGMgB8NTcFkQ46RXbP5srlg9g" [options]="opts" [ERROR ->][offline]="offlineOpts" (onMapLoaded)="loadMap($event)" (onMarkerClicked)="clickMarker($event)"></bai"): MapPage@2:74
'baidu-map' is not a known element:

这个错误如何解决？

**Comment by leftstick** [comment]
你的ng什么版本？最好给出测试代码

**Comment by itshu** [comment]
上个文件解决了，当时在PC上显示没问题了，不过在手机上无法显示，总提示no network，大概什么情况

**Comment by itshu** [comment]
@leftstick  另外这个控件能获取当前坐标位置吗？感谢您的回答

**Comment by leftstick** [comment]
`NO_NETWORK`是离线模式，组件的工作模式是这样的，你的整个应用(js)加载完毕 => 地图组件自动异步加载百度地图的类库，如果加载失败，就显示`NO_NETWORK`。如果你看我在项目首页的gif会看到这个，当我打开wifi后，地图组件发现网络恢复，再次重试百度地图下载，成功的话就显示出来了


获取当前位置，你指的是什么？鼠标点击的位置？还是其他什么

**Comment by Toruitas** [comment]
我也碰到了那个 baidu-map is not a known element 错误。 @itshu 你怎么解决了？
用的版本是ng2.3.1, 也准备用2.4.

`

    import { BaiduMap, OfflineOptions, ControlAnchor } from 'angular2-baidu-map';
  
    @Component({
      selector: 'app-location',
      templateUrl: './location.component.html',
      styleUrls: ['./location.component.scss']
    })

    export class LocationComponent implements OnInit {
  
    lat: number;
    lng: number;
    zooom: number;
  
    opts: any;
  
    constructor() {
    }
  
    ngOnInit() {
      this.lat =  31.264645;
      this.lng =  121.499433;
      this.zooom = 16;
  
      this.opts = {
        center: { latitude: this.lat, longitude: this.lng},
        zoom: this.zooom,
        markers:[{
          latitude: this.lat,
          longitude: this.lng,
          title: "TSG"
        }]
      }
    }
    }
  

`
template.html:
`

      <baidu-map ak="8HXuGfHTVDxajrxEQSXWq4klSvBSu7GV" [options]="opts"></baidu-map>

`
Stacktrace: 

```
Can't bind to 'options' since it isn't a known property of 'baidu-map'.
1. If 'baidu-map' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'baidu-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 (""></sebm-google-map-marker>
  </sebm-google-map>
  <baidu-map ak="8HXuGfHTVDxajrxEQSXWq4klSvBSu7GV" [ERROR ->][options]="opts"></baidu-map>
</div>
<div class="col-sm-12 col-md-6">
"): LocationComponent@6:51
'baidu-map' is not a known element:
1. If 'baidu-map' is an Angular component, then verify that it is part of this module.
2. If 'baidu-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("ogle-map-marker [latitude]="lat" [longitude]="lng"></sebm-google-map-marker>
  </sebm-google-map>
  [ERROR ->]<baidu-map ak="8HXuGfHTVDxajrxEQSXWq4klSvBSu7GV" [options]="opts"></baidu-map>
</div>
<div class="col"): LocationComponent@6:2
Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'baidu-map'.
1. If 'baidu-map' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'baidu-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 (""></sebm-google-map-marker>
  </sebm-google-map>
  <baidu-map ak="8HXuGfHTVDxajrxEQSXWq4klSvBSu7GV" [ERROR ->][options]="opts"></baidu-map>
</div>
<div class="col-sm-12 col-md-6">
"): LocationComponent@6:51
'baidu-map' is not a known element:
1. If 'baidu-map' is an Angular component, then verify that it is part of this module.
2. If 'baidu-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("ogle-map-marker [latitude]="lat" [longitude]="lng"></sebm-google-map-marker>
  </sebm-google-map>
  [ERROR ->]<baidu-map ak="8HXuGfHTVDxajrxEQSXWq4klSvBSu7GV" [options]="opts"></baidu-map>
</div>
<div class="col"): LocationComponent@6:2
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:74435:27) [<root>]
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6300:16) [<root>]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:20462:19) [<root>]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:53977:68) [<root>]
    at http://localhost:4200/vendor.bundle.js:53860:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:53860:19) [<root>]
    at createResult (http://localhost:4200/vendor.bundle.js:53743:19) [<root>]
    at Zone.run (http://localhost:4200/vendor.bundle.js:97414:43) [<root> => <root>]
    at http://localhost:4200/vendor.bundle.js:97821:57 [<root>]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:97452:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:97719:35) [<root>]
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:74435:27) [<root>]
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6300:16) [<root>]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:20462:19) [<root>]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:53977:68) [<root>]
    at http://localhost:4200/vendor.bundle.js:53860:62 [<root>]
    at Set.forEach (native) [<root>]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:53860:19) [<root>]
    at createResult (http://localhost:4200/vendor.bundle.js:53743:19) [<root>]
    at Zone.run (http://localhost:4200/vendor.bundle.js:97414:43) [<root> => <root>]
    at http://localhost:4200/vendor.bundle.js:97821:57 [<root>]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:97452:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:97719:35) [<root>]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:97787:31) [<root>]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:97772:17) [<root>]
    at http://localhost:4200/vendor.bundle.js:97821:17 [<root>]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:97452:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:97719:35) [<root>]
```

**Comment by leftstick** [comment]
@Toruitas  有像示例里在`NgModule`里引入`angular2-baidu-map`么？[示例-L13](https://github.com/leftstick/angular2-baidu-map/blob/master/demo/js/main.ts#L13)

```typescript
@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ MainApp, BaiduMap ],
  bootstrap:    [ MainApp ]
})
class AppModule { }
```

**Comment by Toruitas** [comment]
这样就解决了！谢谢你！很好用。

**Comment by itshu** [comment]
@leftstick 我说的获取当前位置是当前gps的位置坐标，是不是还得用其他的插件

**Comment by itshu** [comment]
@Toruitas  我的好像也是上面那种方式解决的

**Comment by leftstick** [comment]
@itshu  不好意思，目前组件没有对gps的原生支持。不过因为有`onMapLoaded`事件给你，所以你其实可以自己在这个事件的回调里自己处理定位的部分，譬如：

```typescript
loadMap(e: any) {
        let BMap: any = (<any>window)['BMap'];
	let myCity: any = new BMap.LocalCity();
	myCity.get(function (result: any) {
                var cityName = result.name;
		map.setCenter(cityName);
		alert("当前定位城市:"+cityName);
        });
}
```

**Comment by itshu** [comment]
@leftstick 非常感谢
