### ISSUE TITLE
AOT报 map.component.ngfactory.js is not part of the compilation output。

### ISSUE THREAD

**Issue by biganter** [leftstick/angular2-baidu-map#43]
使用ng serve能够正常的启动，没有错误，但使用 ng build --aot 的命令后，显示以下的错误：

`ERROR in ./node_modules/_angular2-baidu-map@4.1.0@angular2-baidu-map/dist/src/components/map.component.ngfactory.js

Module build failed: Error: E:\Wks\node_modules\_angular2-baidu-map@4.1.0@angular2-baidu-map\dist\src\components\map.component.ngfactory.js is not part of the compilation output. Please check the other error messages for details.

    at AngularCompilerPlugin.getCompiledFile (E:\Wks\node_modules\_@ngtools_webpack@1.8.2@@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
    at plugin.done.then (E:\Wks\node_modules\_@ngtools_webpack@1.8.2@@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/app/pages/manage/business/organize/party-organize/map-selector/map-selector.component.ngfactory.js 12:0-122
 @ ./src/app/pages/manage/business/organize/party-organize/organize-detail/organize-detail.module.ngfactory.js
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/_@angular_core@5.0.2@@angular/core/esm2015/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts`

**Comment by leftstick** [comment]
看起来你用的`angular2-baidu-map`是最新的`4.1.0`，那么你的`angular`依赖是什么版本？
